<?php /** INCIO GERAR BOLETO SE BOLETO */
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
Mage::app()->setCurrentStore(Mage_Core_Model_App::ADMIN_STORE_ID);

$order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
if($order->getPayment()->getMethod() == "ceicom_boleto"): ?>
    <center>
        <button type="button" class="button" onclick="window.open('<?php echo $this->getUrl('boleto/customer/view/order_id/' . $order->getId()) ?>')"><span><span><?php echo $this->__('Clique aqui para imprimir o Boleto') ?></span></span><img src="<?php echo($this->getSkinUrl('images/boleto/boleto.gif')) ?>" /></button><br />
    </center>
<?php endif; /** FIM GERAR BOLETO SE BOLETO*/?>