<?php /** INCIO GERAR BOLETO SE BOLETO */
$standard=Mage::getModel('boleto/standard');
$order_id=$this->getRequest()->getParam('order_id');
?>
<?php echo Mage::app()->getRequest()->getControllerName(); ?>
<?php echo $this->getMethod()->getTitle(); ?>
<br/>
<?php if(Mage::app()->getRequest()->getControllerName() == 'order' || Mage::helper('boleto')->getStandard()->getConfigData('secancelado')): ?>
    <center>
        <button type="button" class="button" onclick="window.open('<?php echo $this->getUrl('boleto/customer/view/order_id/' . $order_id) ?>')"><span><span><?php echo $this->__('Clique aqui para imprimir o Boleto') ?></span></span><img src="<?php echo($this->getSkinUrl('images/boleto/boleto.gif')) ?>" /></button><br />
    </center>
<?php endif; ?>